# Generated by Django 3.1.6 on 2021-02-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Tree of Hope Icon Environment Logo.png', upload_to='profile_prictures'),
        ),
    ]
