# Generated by Django 3.1.6 on 2021-02-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(max_length=200)),
                ('item_desc', models.TextField(max_length=200)),
                ('item_price', models.IntegerField()),
            ],
        ),
    ]
